kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-example-rules
  labels:
    role: prometheus-rulefiles
    prometheus: prometheus-helloworld 
data:
  example.rules: |
    ALERT ExampleAlert
    IF vector(1)
